[project]
name = "nebula-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.7",
    "mkdocs-mermaid2-plugin>=1.2.1",
]
